---
apiVersion: syncagent.kcp.io/v1alpha1
kind: PublishedResource
metadata:
  name: publish-kubev-linux-vms
  labels:
    kdp.k8c.io/syncagent: kubev-vms
spec:
  resource:
    kind: LinuxVirtualMachine
    apiGroup: kubev.k8c.io
    versions: [v1alpha1]
  naming:
    namespace: kubermatic-virtualization
    name: 'kdp-{{ .ClusterName }}-{{ .Object.metadata.namespace }}-{{ .Object.metadata.name }}'
