apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fio-test-file
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: kubev-vms #FOG


---
apiVersion: v1
kind: Pod
metadata:
  name: fio-test-file-pod
spec:
  containers:
    - name: tooling
      image: quay.io/kubermatic-labs/kubeone-tooling
      imagePullPolicy: Always
      command:
        - "/bin/sh"
      args:
        - "-c"
        - "while true; do echo $(date): $(ls -lah /dev/xvda) >> /tmp/buffer; cat /tmp/buffer; sleep 5; done;"
      volumeMounts:
        - mountPath: /data
          name: my-volume-file
      securityContext:
        runAsUser: 0
  terminationGracePeriodSeconds: 2
  volumes:
    - name: my-volume-file
      persistentVolumeClaim:
        claimName: fio-test-file