apiVersion: apps/v1
kind: Deployment
metadata:
  name: vm-image-registry
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: vm-image-registry
  replicas: 1 # tells deployment to run 2 pods matching the template
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: vm-image-registry
    spec:
      terminationGracePeriodSeconds: 20
      restartPolicy: Always
      containers:
      - name: nginx
        image: nginx:1.23.3
        ports:
        - containerPort: 80
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /index.html
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        volumeMounts:
          - mountPath: /usr/share/nginx/html/vms
            name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: vm-image-data
---
apiVersion: v1
kind: Service
metadata:
  name: vm-image-registry
  namespace: kube-system
spec:
  ports:
  - port: 80
  selector:
    app: vm-image-registry
  type: NodePort
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
#  annotations:
  labels:
    app: vm-image-registry
  name: vm-image-data
  namespace: kube-system
spec:
  storageClassName: kubev-main
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi