---
kind: Vpc
apiVersion: kubev.k8c.io/v1alpha1
metadata:
  name: windows-aas-vpc
  namespace: windows-aas
  annotations:
    ovn.kubernetes.io/vpc_lb: "off"
spec:
  externalSubnet: ovn-default
  enableBfd: true
  staticRoutes: []
  vpcPeerings: []

---
kind: Subnet
apiVersion: kubev.k8c.io/v1alpha1
metadata:
  name: windows-aas-subnet
  namespace: windows-aas
spec:
  cidr: 10.44.0.0/24
  vpc: windows-aas-vpc
  natOutgoing: true

---
kind: WindowsVirtualMachine
apiVersion: kubev.k8c.io/v1alpha1
metadata:
  name: windows-10-golden
  namespace: windows-aas
spec:
  instanceType: u1.large
  diskSize: 50Gi
  templateImageName: windows-10-golden
  loadBalancerClass: kubelb
  subnet: windows-aas-subnet
  vpc: windows-aas-vpc
