## Secret containing the kubeconfig for the KubeLB management cluster (30_kubelb)
## The CCM uses this to register with the KubeLB manager and sync LB/Ingress/Gateway resources
## Generate: kubectl -n <tenant> get secret kubelb-ccm-kubeconfig --template={{.data.kubelb}} | base64 -d
apiVersion: v1
kind: Namespace
metadata:
  name: kubelb
---
apiVersion: v1
kind: Secret
metadata:
  name: kubelb-manager
  namespace: kubelb
type: Opaque
data:
  #TODO