---
apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  # The name of the CRD will be 'compositevms.composition.kubevirt.io'
  # The API group will be 'composition.kubevirt.io'
  name: virtualmachines.kubev.k8c.io
spec:
  # 1. Define the schema for the new CompositeVM CRD
  schema:
    additionalPrinterColumns:
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - jsonPath: .status.properties.phase.expression
      name: Phase
      type: string
    - jsonPath: .spec.memory
      name: Memory
      type: string
    - jsonPath: .spec.cpu
      name: Cores
      type: integer
    - jsonPath: .status.properties.interfaces.expression[0].ipAddress
      name: IP Adress
      type: string
    - jsonPath: .spec.diskSize
      name: Disk Size
      type: string
    # The version for the new CRD (e.g., v1alpha1)
    apiVersion: v1alpha1
    kind: VirtualMachine
    group: kubev.k8c.io
    spec:
      source: string | default="https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img"
      cpu: integer
      memory: string
      diskSize: string
      subnet: string
      vpc: string
    status:
      type: object
      properties:
        interfaces:
          type: array
          expression: ${vmi.status.interfaces}
          x-kubernetes-preserve-unknown-fields: true
        currentCPUTopology:
          type: object
          expression: ${vmi.status.currentCPUTopology}
          x-kubernetes-preserve-unknown-fields: true
        guestOSInfo:
          type: object
          expression: ${vmi.status.guestOSInfo}
          x-kubernetes-preserve-unknown-fields: true
        machine:
          type: object
          expression: ${vmi.status.machine}
          x-kubernetes-preserve-unknown-fields: true
        # memory:
        #   type: object
        #   expression: ${vmi.status.memory}
        #   x-kubernetes-preserve-unknown-fields: true
        migrationMethod:
          type: string
          expression: ${vmi.status.migrationMethod}
        migrationTransport:
          type: string
          expression: ${vmi.status.migrationTransport}
        phase:
          type: string
          expression: ${vmi.status.phase}
        volumeStatus:
          type: array
          expression: ${vmi.status.volumeStatus}
          x-kubernetes-preserve-unknown-fields: true

  # 2. Define the underlying resources
  resources:
    # This resource creates the KubeVirt VirtualMachine
    - id: vm
      template:
        apiVersion: kubevirt.io/v1
        kind: VirtualMachine
        metadata:
          name: ${schema.metadata.name}
          namespace: ${schema.metadata.namespace}
        # The VM's spec is populated from the composite resource's 'vmSpec' field
        spec:
          running: true
          dataVolumeTemplates:
          - metadata:
              creationTimestamp: null
              name: ${schema.metadata.name}-disk0
            spec:
              source:
                http:
                  url: https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img
              storage:
                accessModes:
                - ReadWriteOnce
                resources:
                  requests:
                    storage: ${schema.spec.diskSize}
                # storageClassName: longhorn
          template:
            metadata:
              creationTimestamp: null
              labels:
                kubevirt.io/vm: ${schema.metadata.name}
              annotations:
                ovn.kubernetes.io/logical_router: ${schema.spec.vpc}-${schema.metadata.labels['syncagent.kcp.io/remote-object-cluster']}
                ovn.kubernetes.io/logical_switch: ${schema.spec.subnet}-${schema.metadata.labels['syncagent.kcp.io/remote-object-cluster']}
                kubevirt.io/allow-pod-bridge-network-live-migration: "true"
            spec:
              domain:
                cpu:
                  cores: ${schema.spec.cpu}
                resources:
                  requests:
                    memory: ${schema.spec.memory}
                  limits:
                    memory: ${schema.spec.memory}
                devices:
                  networkInterfaceMultiqueue: true
                  disks:
                  - name: datavolumedisk
                    disk:
                      bus: virtio
                  - disk:
                      bus: virtio
                    name: cloudinitdisk
                  interfaces:
                  - bridge: {}
                    name: default
                machine:
                  type: q35
              affinity: {}
              architecture: amd64
              dnsPolicy: ClusterFirstWithHostNet
              evictionStrategy: External
              networks:
              - name: default
                pod: {}
              terminationGracePeriodSeconds: 30
              volumes:
              # - containerDisk:
              #     image: quay.io/containerdisks/ubuntu:22.04
              #   name: containerdisk
              - dataVolume:
                  name: ${schema.metadata.name}-disk0
                name: datavolumedisk
              - cloudInitNoCloud:
                  userData: |
                    #cloud-config
                    users:
                    - groups: users, admin
                      name: kubevirt
                      passwd: $6$0D3RNnngtIZSq0C6$O.rkXQNZhKRWOBDJAYQCLeNAeTQKjmKdm6ZdtRf1QONDpak5wpgvhO9AtdMB4czCKE4/TYvsZ6Bwc/ygiD29r1
                      lock-passwd: false
                      ssh_pwauth: True
                      chpasswd: { expire: False }
                      shell: /bin/bash
                      sudo: ALL=(ALL) NOPASSWD:ALL
                name: cloudinitdisk
      # The resource depends on nothing

    # This is a read-only resource to get the status from the VirtualMachineInstance
    - id: vmi
      # readyWhen:
      #   - vm.status.ready
      externalRef:
        apiVersion: kubevirt.io/v1
        kind: VirtualMachineInstance
        metadata:
          name: ${schema.metadata.name}
          namespace: ${schema.metadata.namespace}