apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: windows-10-x86-64-iso
  namespace: build-vm-win10
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: "true"
spec:
  source:
    http:
      url: "http://vm-image-registry.kube-system.svc/vms/win10-2025-10.iso"
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: kubev-vms
