apiVersion: v1
kind: Namespace
metadata:
  name: win10-demo
---
# RBAC: Allow the default SA in win10-demo to clone DataVolumes from vm-images
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cdi-clone-from-vm-images
rules:
- apiGroups: ["cdi.kubevirt.io"]
  resources: ["datavolumes/source"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cdi-clone-from-vm-images
  namespace: build-vm-win10
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cdi-clone-from-vm-images
subjects:
- kind: ServiceAccount
  name: default
  namespace: win10-demo
---
apiVersion: v1
kind: Service
metadata:
  name: win10-demo
  namespace: win10-demo
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "win10-demo.tobi.demo.kubermatic.io"
spec:
  ports:
  - name: rdp
    port: 3389
  - name: http
    port: 80
  selector:
    kubevirt.io/vm: win10-demo
  type: LoadBalancer
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: win10-demo
  namespace: win10-demo
  labels:
    kubevirt.io/vm: win10-demo
spec:
  # Instance type and preference manage CPU, memory, firmware, Hyper-V, clock, etc.
  instancetype:
    kind: VirtualMachineClusterInstancetype
    name: u1.large
  preference:
    kind: VirtualMachineClusterPreference
    name: windows.10.virtio

  # Clone the golden image into a new disk for this VM
  dataVolumeTemplates:
  - metadata:
      name: win10-demo-disk
    spec:
      sourceRef:
        kind: DataSource
        name: windows-10-golden
        namespace: build-vm-win10
      storage:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
        storageClassName: kubev-vms

  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/vm: win10-demo
        kubevirt.io/os: windows10
    spec:
      dnsConfig:
        nameservers:
        - 8.8.8.8
      dnsPolicy: None
      domain:
        devices:
          disks:
          - name: rootdisk
            disk: {}
            bootOrder: 1
          interfaces:
          - name: default
            masquerade: {}
      networks:
      - name: default
        pod: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: rootdisk
        dataVolume:
          name: win10-demo-disk