#apiVersion: v1
#kind: Namespace
#metadata:
#  name: vm-demo
#---
#apiVersion: instancetype.kubevirt.io/v1beta1
#kind: VirtualMachineInstancetype
#metadata:
#  name: standard-2
#  namespace: vm-demo
#spec:
#  cpu:
#    guest: 2
#  memory:
#    guest: 8Gi
#---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  namespace: vm-demo
  labels:
    kubevirt.io/vm: vm-ubuntu-22
  name: vm-ubuntu-22
spec:
  dataVolumeTemplates:
  - metadata:
      creationTimestamp: null
      name: vm-ubuntu-22
    spec:
      source:
        registry:
          pullMethod: node
          #url: docker://quay.io/kubermatic-virt-disks/ubuntu:22.04
          url: docker://quay.io/kubermatic-virt-disks/ubuntu:24.04-amd64
        #http:
        #  url: http://vm-image-registry.kube-system.svc/vms/ubuntu-22.04-2025-01-13.img
          #latest cloudimg
          #url: https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-amd64.img
      storage:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 15G
        storageClassName: local-path
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm-ubuntu-22
    spec:
      affinity: {}
      architecture: amd64
      dnsConfig:
        nameservers:
        - 8.8.8.8
      dnsPolicy: None
      domain:
        cpu:
          cores: 2
        devices:
          disks:
          - disk:
              bus: virtio
            name: datavolumedisk
          - disk:
              bus: virtio
            name: cloudinitdisk
#          interfaces:
#          - bridge: {}
#            name: default
#          networkInterfaceMultiqueue: true
#        machine:
#          type: q35
        resources:
          limits:
            memory: 4G
          requests:
            memory: 4G
#      evictionStrategy: External
#      networks:
#      - name: default
#        pod: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - dataVolume:
          name: vm-ubuntu-22
        name: datavolumedisk
      - cloudInitNoCloud:
          userData: |
            #!/bin/sh
            uname -a
            mkdir -p /root/.ssh
            cat << EOF >> /root/.ssh/authorized_keys
            ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCloj8OvReuuOXtECaMo1iZD8q8newJ9hWZSxIiwOG2406uOueYOxBleb85Jl231YWWjocj6fqExvZBzsQQlrad4fy6oDL5sKZyngtkCZnWcq1DsWn8Sgas9lw2+KS67EXO/P5SHhJSOrqyU6ciktX0WViPvVqb6DnK3RepFh6Xnyl0Q/0RnpSCTomyKK2PfNsv8e80AnfxA1CtnRfeexgwiKtQUPzkEdCG1ABcdZZru3m0y7y1qR0MdYYZIK+bycacngvJCJyp8gnIXHU8dDZanHL2WGOcCpd/gjwM6iryr6IhlCZXw++PRGK1aErtvKDH7oaAMLW8qFK4+bpMdeytd4Viw/g3SH3Q7ows2xl6NTaU2F0PTXD+qAY2xna1eemet1txl1oP6KQJ2Rqc5rNU3/auhdK4PaU22D8Z2XF7gOrsoQB7dqW0BBDHg/ftVNb9BgOHGkYvxSsCavcqX3joUyFjHzhv+sD1WiOPvfRqV4fQ8h47ERvD3QXuBn+5YKeKp/0sjSCypIdK02FAFa2NxN2tEoh7wdCBX9enFU3UT7jfeW5Pf98Z6ao9hiAF80J5FIM21sMG3E3dAMb2tr8Gc8jM5QdWO4rJkG9j5v2d1umLkSxm7pN4Mxw/AE02jYNEblm9i/Pbzg8wqa9gw2gubO7A8qoKVtA1xlOnDVB+0Q== tobi@loodse.com EOF
            echo 'ssh key added ...'
            cp /root/.ssh/authorized_keys /home/ubuntu/.ssh/authorized_keys
            cat /root/.ssh/authorized_keys
            echo 'connect via: virtctl ssh root@vm-ubuntu-22'
        name: cloudinitdisk
